[package]
name = "ve"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = { version = "3.4.0", features = ["wayland-data-control"] }
enigo = { version = "0.2.1", default-features = false, features = ["wayland"] }
